name: Blocklist Updater
on: 
  schedule:
    - cron: "0 12 * * *"  # Daily noon update
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Validate config
        run: python -m json.tool config.json
      
      - name: Download compiler
        run: wget -q https://raw.githubusercontent.com/ghostnetic/adblock-filter-compiler/main/adblock_filter_compiler.py
      
      - name: Run compilation
        run: python adblock_filter_compiler.py
      
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-update: $(date +'%Y-%m-%d %T')"
